-- Databricks SQL Full Example DDL Script
CREATE TABLE Customers (
    CustomerID INT GENERATED BY DEFAULT AS IDENTITY,
    Name STRING NOT NULL,
    Email STRING NOT NULL,
    CreatedDate DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (CustomerID),
    CONSTRAINT email_unique UNIQUE (Email)
);

CREATE TABLE Orders (
    OrderID INT GENERATED BY DEFAULT AS IDENTITY,
    CustomerID INT NOT NULL,
    OrderDate DATE DEFAULT CURRENT_DATE,
    TotalAmount DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (OrderID),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE OrderItems (
    OrderItemID INT GENERATED BY DEFAULT AS IDENTITY,
    OrderID INT NOT NULL,
    Product STRING NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (OrderItemID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);